### ISSUE TITLE
Installing issue (acces to path ... denied)

### ISSUE THREAD

**Issue by brannontoune** [FTBTeam/FTB-Academy#9] opened 2019-08-22 10:08 UTC
* **Modpack Version**:  1.0.0

* **Issue**: 
When I try to install the modpack inside of the twitch app, I get an error.
* **Link to Log or Crash File Paste**: 
Access to the path "/var/folders/pg/x5y6zdns3nd1jcd_fy07bwm00000gn/T/Curse Client/2CDCD7E822FE488E81B963FF8719F4DB/5/manifest.json" or "/Users/brannontoune/Documents/Curse/Minecraft/Instances/FTB Academy/manifest.json" is denied.
* **Is it Repeatable?**: 
yes
* **Mod/s Affected**: 
all
* **Known Fix**: 
no

**Comment by aaronhowser1** [comment] 2019-08-22 10:10
Duplicate of #7

Unfortunately, there's nothing we can do about this. Try restarting Twitch or your computer, or starting Twitch in admin mode

**Closed by aaronhowser1** 2019-08-22 10:10 UTC
