### ISSUE TITLE
Console being flooded by KubeJS error

### ISSUE THREAD

**Issue by huantianad** [FTBTeam/FTB-Academy#358] opened 2021-01-31 17:27 UTC
* **Modpack Version**: 1.4.0

* **Issue**: I am currently running a FTB Academy server. After some time of playing, the console is getting flooded by this message: ```[Server thread/ERROR] [KubeJS]: Error occurred while firing 'player.inventory.changed' event in kubejs/astral_quests.js: <eval>:3 TypeError: (i.getNbt().get("astralsorcery")).get is not a function```. This seems to only happen when one specific user is online, it could be due to them having progressed in astral sorcery.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2335269d

* **Is it Repeatable?**: Yes, this happens whenever this user is online.

* **Mod/s Affected**: Seems to be an error with KubeJS (1.1.0.65) and Astral Sorcery (1.10.27)

**Comment by aaronhowser1** [comment] 2021-04-03 08:26
Duplicate of #314

**Closed by aaronhowser1** 2021-04-03 08:26 UTC
