### ISSUE TITLE
Ender Chest quest in storage section

### ISSUE THREAD

**Issue by OlRusty** [FTBTeam/FTB-Academy#108] opened 2019-09-06 13:55 UTC
* **Modpack Version**: FTB Academy 1.0.0

* **Issue**: It's a minor issue but the quest for the ender chest also counts it as the ender tank part and only get the single reward.

* **Link to Log or Crash File Paste**: there was no crash or log file created

* **Is it Repeatable?**: unsure - hard to get ender pearls in my maps

* **Mod/s Affected**: i think it's the ender storage mod ender chest

* **Known Fix**: <!-- optional; this is a quest book detection error i dont know how to fix

**Comment by aaronhowser1** [comment] 2019-09-06 19:08
Duplicate of #65, which is already fixed in dev.

**Closed by aaronhowser1** 2019-09-06 19:08 UTC
