### ISSUE TITLE
Quest for Leadstone Jetpack bugged

### ISSUE THREAD

**Issue by Toxicom** [FTBTeam/FTB-Academy#364] opened 2021-03-24 20:19 UTC
* **Modpack Version**: 
FTB Academy v1.4.0

* **Issue**: 
* Quest "**Like an Eagle, Piloting a Blimp**" says "*Make a Leadstone Jetpack*" but when you open the quest, it says you need **Vibrant Jetpack** which is not even in the game *(JEI doesn't detect it)*
* Making a Leadstone Jetpack did **not** complete the quest.

* **Link to Log or Crash File Paste**: 
* Didn't crash.

* **Is it Repeatable?**: 
* 99% sure I can.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment] 2021-03-24 20:20
Duplicate of #344

**Closed by aaronhowser1** 2021-03-24 20:20 UTC
