### ISSUE TITLE
[CRITICAL] INFINITE DIAMOND

### ISSUE THREAD

**Issue by enescaglayan** [FTBTeam/FTB-Academy#204] opened 2019-11-07 19:20 UTC
* **Modpack Version**: all versions before this bug was fixed (currently i am on 1.1.1)

* **Issue**: You need make a diamond horse armor with 4 diamonds then, use Crusher to convert them to 6 diamond dust, and cook the dusts. BOOM you got +2 diamonds!

* **Is it Repeatable?**: %100 yes 

* **Mod/s Affected**: I really dont know

* **Known Fix**: remove or edit the recipe of diamond horse armor

sorry for using uppercase letters, its very cricital and it needs be fixed as soon as possible

**Comment by aaronhowser1** [comment] 2019-11-07 22:04
Duplicate of #133

**Closed by aaronhowser1** 2019-11-07 22:04 UTC
